version: "3.9"

services:
    app:
        build: .
        volumes:
            - .:/app
        ports:
            - 8501:8501
            - 8888:8888
        links:
            - es
        container_name: movie_app
    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        volumes:
            - ./data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node
        container_name: movie_es